// Generated by gencpp from file robotiq_3f_srvs/Activate.msg
// DO NOT EDIT!


#ifndef ROBOTIQ_3F_SRVS_MESSAGE_ACTIVATE_H
#define ROBOTIQ_3F_SRVS_MESSAGE_ACTIVATE_H

#include <ros/service_traits.h>


#include <robotiq_3f_srvs/ActivateRequest.h>
#include <robotiq_3f_srvs/ActivateResponse.h>


namespace robotiq_3f_srvs
{

struct Activate
{

typedef ActivateRequest Request;
typedef ActivateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Activate
} // namespace robotiq_3f_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotiq_3f_srvs::Activate > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::robotiq_3f_srvs::Activate&) { return value(); }
};

template<>
struct DataType< ::robotiq_3f_srvs::Activate > {
  static const char* value()
  {
    return "robotiq_3f_srvs/Activate";
  }

  static const char* value(const ::robotiq_3f_srvs::Activate&) { return value(); }
};


// service_traits::MD5Sum< ::robotiq_3f_srvs::ActivateRequest> should match
// service_traits::MD5Sum< ::robotiq_3f_srvs::Activate >
template<>
struct MD5Sum< ::robotiq_3f_srvs::ActivateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotiq_3f_srvs::Activate >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::ActivateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotiq_3f_srvs::ActivateRequest> should match
// service_traits::DataType< ::robotiq_3f_srvs::Activate >
template<>
struct DataType< ::robotiq_3f_srvs::ActivateRequest>
{
  static const char* value()
  {
    return DataType< ::robotiq_3f_srvs::Activate >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::ActivateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotiq_3f_srvs::ActivateResponse> should match
// service_traits::MD5Sum< ::robotiq_3f_srvs::Activate >
template<>
struct MD5Sum< ::robotiq_3f_srvs::ActivateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotiq_3f_srvs::Activate >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::ActivateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotiq_3f_srvs::ActivateResponse> should match
// service_traits::DataType< ::robotiq_3f_srvs::Activate >
template<>
struct DataType< ::robotiq_3f_srvs::ActivateResponse>
{
  static const char* value()
  {
    return DataType< ::robotiq_3f_srvs::Activate >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::ActivateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTIQ_3F_SRVS_MESSAGE_ACTIVATE_H
