// Generated by gencpp from file robotiq_3f_srvs/GetModeResponse.msg
// DO NOT EDIT!


#ifndef ROBOTIQ_3F_SRVS_MESSAGE_GETMODERESPONSE_H
#define ROBOTIQ_3F_SRVS_MESSAGE_GETMODERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotiq_3f_srvs
{
template <class ContainerAllocator>
struct GetModeResponse_
{
  typedef GetModeResponse_<ContainerAllocator> Type;

  GetModeResponse_()
    : mode()
    , success(false)  {
    }
  GetModeResponse_(const ContainerAllocator& _alloc)
    : mode(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mode_type;
  _mode_type mode;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetModeResponse_

typedef ::robotiq_3f_srvs::GetModeResponse_<std::allocator<void> > GetModeResponse;

typedef boost::shared_ptr< ::robotiq_3f_srvs::GetModeResponse > GetModeResponsePtr;
typedef boost::shared_ptr< ::robotiq_3f_srvs::GetModeResponse const> GetModeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator1> & lhs, const ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator1> & lhs, const ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotiq_3f_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c8272edd1805ed053997f57be90c52f";
  }

  static const char* value(const ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c8272edd1805ed0ULL;
  static const uint64_t static_value2 = 0x53997f57be90c52fULL;
};

template<class ContainerAllocator>
struct DataType< ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotiq_3f_srvs/GetModeResponse";
  }

  static const char* value(const ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mode\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetModeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotiq_3f_srvs::GetModeResponse_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mode);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTIQ_3F_SRVS_MESSAGE_GETMODERESPONSE_H
