// Generated by gencpp from file robotiq_3f_srvs/GetMode.msg
// DO NOT EDIT!


#ifndef ROBOTIQ_3F_SRVS_MESSAGE_GETMODE_H
#define ROBOTIQ_3F_SRVS_MESSAGE_GETMODE_H

#include <ros/service_traits.h>


#include <robotiq_3f_srvs/GetModeRequest.h>
#include <robotiq_3f_srvs/GetModeResponse.h>


namespace robotiq_3f_srvs
{

struct GetMode
{

typedef GetModeRequest Request;
typedef GetModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMode
} // namespace robotiq_3f_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotiq_3f_srvs::GetMode > {
  static const char* value()
  {
    return "0c8272edd1805ed053997f57be90c52f";
  }

  static const char* value(const ::robotiq_3f_srvs::GetMode&) { return value(); }
};

template<>
struct DataType< ::robotiq_3f_srvs::GetMode > {
  static const char* value()
  {
    return "robotiq_3f_srvs/GetMode";
  }

  static const char* value(const ::robotiq_3f_srvs::GetMode&) { return value(); }
};


// service_traits::MD5Sum< ::robotiq_3f_srvs::GetModeRequest> should match
// service_traits::MD5Sum< ::robotiq_3f_srvs::GetMode >
template<>
struct MD5Sum< ::robotiq_3f_srvs::GetModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotiq_3f_srvs::GetMode >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::GetModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotiq_3f_srvs::GetModeRequest> should match
// service_traits::DataType< ::robotiq_3f_srvs::GetMode >
template<>
struct DataType< ::robotiq_3f_srvs::GetModeRequest>
{
  static const char* value()
  {
    return DataType< ::robotiq_3f_srvs::GetMode >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::GetModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotiq_3f_srvs::GetModeResponse> should match
// service_traits::MD5Sum< ::robotiq_3f_srvs::GetMode >
template<>
struct MD5Sum< ::robotiq_3f_srvs::GetModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotiq_3f_srvs::GetMode >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::GetModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotiq_3f_srvs::GetModeResponse> should match
// service_traits::DataType< ::robotiq_3f_srvs::GetMode >
template<>
struct DataType< ::robotiq_3f_srvs::GetModeResponse>
{
  static const char* value()
  {
    return DataType< ::robotiq_3f_srvs::GetMode >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::GetModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTIQ_3F_SRVS_MESSAGE_GETMODE_H
