// Generated by gencpp from file robotiq_3f_srvs/GetPositionResponse.msg
// DO NOT EDIT!


#ifndef ROBOTIQ_3F_SRVS_MESSAGE_GETPOSITIONRESPONSE_H
#define ROBOTIQ_3F_SRVS_MESSAGE_GETPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotiq_3f_srvs
{
template <class ContainerAllocator>
struct GetPositionResponse_
{
  typedef GetPositionResponse_<ContainerAllocator> Type;

  GetPositionResponse_()
    : target_position(0)
    , finger_a_position(0)
    , finger_b_position(0)
    , finger_c_position(0)
    , success(false)  {
    }
  GetPositionResponse_(const ContainerAllocator& _alloc)
    : target_position(0)
    , finger_a_position(0)
    , finger_b_position(0)
    , finger_c_position(0)
    , success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _target_position_type;
  _target_position_type target_position;

   typedef uint8_t _finger_a_position_type;
  _finger_a_position_type finger_a_position;

   typedef uint8_t _finger_b_position_type;
  _finger_b_position_type finger_b_position;

   typedef uint8_t _finger_c_position_type;
  _finger_c_position_type finger_c_position;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetPositionResponse_

typedef ::robotiq_3f_srvs::GetPositionResponse_<std::allocator<void> > GetPositionResponse;

typedef boost::shared_ptr< ::robotiq_3f_srvs::GetPositionResponse > GetPositionResponsePtr;
typedef boost::shared_ptr< ::robotiq_3f_srvs::GetPositionResponse const> GetPositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator1> & lhs, const ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.target_position == rhs.target_position &&
    lhs.finger_a_position == rhs.finger_a_position &&
    lhs.finger_b_position == rhs.finger_b_position &&
    lhs.finger_c_position == rhs.finger_c_position &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator1> & lhs, const ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotiq_3f_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "15af47e08a021b42de872282bf4961e5";
  }

  static const char* value(const ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x15af47e08a021b42ULL;
  static const uint64_t static_value2 = 0xde872282bf4961e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotiq_3f_srvs/GetPositionResponse";
  }

  static const char* value(const ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 target_position\n"
"uint8 finger_a_position\n"
"uint8 finger_b_position\n"
"uint8 finger_c_position\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_position);
      stream.next(m.finger_a_position);
      stream.next(m.finger_b_position);
      stream.next(m.finger_c_position);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotiq_3f_srvs::GetPositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "target_position: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_position);
    s << indent << "finger_a_position: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finger_a_position);
    s << indent << "finger_b_position: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finger_b_position);
    s << indent << "finger_c_position: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finger_c_position);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTIQ_3F_SRVS_MESSAGE_GETPOSITIONRESPONSE_H
