// Generated by gencpp from file robotiq_3f_srvs/GetPosition.msg
// DO NOT EDIT!


#ifndef ROBOTIQ_3F_SRVS_MESSAGE_GETPOSITION_H
#define ROBOTIQ_3F_SRVS_MESSAGE_GETPOSITION_H

#include <ros/service_traits.h>


#include <robotiq_3f_srvs/GetPositionRequest.h>
#include <robotiq_3f_srvs/GetPositionResponse.h>


namespace robotiq_3f_srvs
{

struct GetPosition
{

typedef GetPositionRequest Request;
typedef GetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPosition
} // namespace robotiq_3f_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotiq_3f_srvs::GetPosition > {
  static const char* value()
  {
    return "15af47e08a021b42de872282bf4961e5";
  }

  static const char* value(const ::robotiq_3f_srvs::GetPosition&) { return value(); }
};

template<>
struct DataType< ::robotiq_3f_srvs::GetPosition > {
  static const char* value()
  {
    return "robotiq_3f_srvs/GetPosition";
  }

  static const char* value(const ::robotiq_3f_srvs::GetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::robotiq_3f_srvs::GetPositionRequest> should match
// service_traits::MD5Sum< ::robotiq_3f_srvs::GetPosition >
template<>
struct MD5Sum< ::robotiq_3f_srvs::GetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotiq_3f_srvs::GetPosition >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::GetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotiq_3f_srvs::GetPositionRequest> should match
// service_traits::DataType< ::robotiq_3f_srvs::GetPosition >
template<>
struct DataType< ::robotiq_3f_srvs::GetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::robotiq_3f_srvs::GetPosition >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::GetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotiq_3f_srvs::GetPositionResponse> should match
// service_traits::MD5Sum< ::robotiq_3f_srvs::GetPosition >
template<>
struct MD5Sum< ::robotiq_3f_srvs::GetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotiq_3f_srvs::GetPosition >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::GetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotiq_3f_srvs::GetPositionResponse> should match
// service_traits::DataType< ::robotiq_3f_srvs::GetPosition >
template<>
struct DataType< ::robotiq_3f_srvs::GetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::robotiq_3f_srvs::GetPosition >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::GetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTIQ_3F_SRVS_MESSAGE_GETPOSITION_H
