// Generated by gencpp from file robotiq_3f_srvs/GetSpeed.msg
// DO NOT EDIT!


#ifndef ROBOTIQ_3F_SRVS_MESSAGE_GETSPEED_H
#define ROBOTIQ_3F_SRVS_MESSAGE_GETSPEED_H

#include <ros/service_traits.h>


#include <robotiq_3f_srvs/GetSpeedRequest.h>
#include <robotiq_3f_srvs/GetSpeedResponse.h>


namespace robotiq_3f_srvs
{

struct GetSpeed
{

typedef GetSpeedRequest Request;
typedef GetSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSpeed
} // namespace robotiq_3f_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotiq_3f_srvs::GetSpeed > {
  static const char* value()
  {
    return "6f5ae4e6edb4b56e87a35277f1b9993b";
  }

  static const char* value(const ::robotiq_3f_srvs::GetSpeed&) { return value(); }
};

template<>
struct DataType< ::robotiq_3f_srvs::GetSpeed > {
  static const char* value()
  {
    return "robotiq_3f_srvs/GetSpeed";
  }

  static const char* value(const ::robotiq_3f_srvs::GetSpeed&) { return value(); }
};


// service_traits::MD5Sum< ::robotiq_3f_srvs::GetSpeedRequest> should match
// service_traits::MD5Sum< ::robotiq_3f_srvs::GetSpeed >
template<>
struct MD5Sum< ::robotiq_3f_srvs::GetSpeedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotiq_3f_srvs::GetSpeed >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::GetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotiq_3f_srvs::GetSpeedRequest> should match
// service_traits::DataType< ::robotiq_3f_srvs::GetSpeed >
template<>
struct DataType< ::robotiq_3f_srvs::GetSpeedRequest>
{
  static const char* value()
  {
    return DataType< ::robotiq_3f_srvs::GetSpeed >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::GetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotiq_3f_srvs::GetSpeedResponse> should match
// service_traits::MD5Sum< ::robotiq_3f_srvs::GetSpeed >
template<>
struct MD5Sum< ::robotiq_3f_srvs::GetSpeedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotiq_3f_srvs::GetSpeed >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::GetSpeedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotiq_3f_srvs::GetSpeedResponse> should match
// service_traits::DataType< ::robotiq_3f_srvs::GetSpeed >
template<>
struct DataType< ::robotiq_3f_srvs::GetSpeedResponse>
{
  static const char* value()
  {
    return DataType< ::robotiq_3f_srvs::GetSpeed >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::GetSpeedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTIQ_3F_SRVS_MESSAGE_GETSPEED_H
