// Generated by gencpp from file robotiq_3f_srvs/GetTorqueResponse.msg
// DO NOT EDIT!


#ifndef ROBOTIQ_3F_SRVS_MESSAGE_GETTORQUERESPONSE_H
#define ROBOTIQ_3F_SRVS_MESSAGE_GETTORQUERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotiq_3f_srvs
{
template <class ContainerAllocator>
struct GetTorqueResponse_
{
  typedef GetTorqueResponse_<ContainerAllocator> Type;

  GetTorqueResponse_()
    : torque(0)
    , success(false)  {
    }
  GetTorqueResponse_(const ContainerAllocator& _alloc)
    : torque(0)
    , success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _torque_type;
  _torque_type torque;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetTorqueResponse_

typedef ::robotiq_3f_srvs::GetTorqueResponse_<std::allocator<void> > GetTorqueResponse;

typedef boost::shared_ptr< ::robotiq_3f_srvs::GetTorqueResponse > GetTorqueResponsePtr;
typedef boost::shared_ptr< ::robotiq_3f_srvs::GetTorqueResponse const> GetTorqueResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator1> & lhs, const ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator2> & rhs)
{
  return lhs.torque == rhs.torque &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator1> & lhs, const ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotiq_3f_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84acdc269d50ea8a59a1ba851600ccec";
  }

  static const char* value(const ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84acdc269d50ea8aULL;
  static const uint64_t static_value2 = 0x59a1ba851600ccecULL;
};

template<class ContainerAllocator>
struct DataType< ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotiq_3f_srvs/GetTorqueResponse";
  }

  static const char* value(const ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 torque\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.torque);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTorqueResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotiq_3f_srvs::GetTorqueResponse_<ContainerAllocator>& v)
  {
    s << indent << "torque: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.torque);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTIQ_3F_SRVS_MESSAGE_GETTORQUERESPONSE_H
