// Generated by gencpp from file robotiq_3f_srvs/Move.msg
// DO NOT EDIT!


#ifndef ROBOTIQ_3F_SRVS_MESSAGE_MOVE_H
#define ROBOTIQ_3F_SRVS_MESSAGE_MOVE_H

#include <ros/service_traits.h>


#include <robotiq_3f_srvs/MoveRequest.h>
#include <robotiq_3f_srvs/MoveResponse.h>


namespace robotiq_3f_srvs
{

struct Move
{

typedef MoveRequest Request;
typedef MoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Move
} // namespace robotiq_3f_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotiq_3f_srvs::Move > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::robotiq_3f_srvs::Move&) { return value(); }
};

template<>
struct DataType< ::robotiq_3f_srvs::Move > {
  static const char* value()
  {
    return "robotiq_3f_srvs/Move";
  }

  static const char* value(const ::robotiq_3f_srvs::Move&) { return value(); }
};


// service_traits::MD5Sum< ::robotiq_3f_srvs::MoveRequest> should match
// service_traits::MD5Sum< ::robotiq_3f_srvs::Move >
template<>
struct MD5Sum< ::robotiq_3f_srvs::MoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotiq_3f_srvs::Move >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::MoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotiq_3f_srvs::MoveRequest> should match
// service_traits::DataType< ::robotiq_3f_srvs::Move >
template<>
struct DataType< ::robotiq_3f_srvs::MoveRequest>
{
  static const char* value()
  {
    return DataType< ::robotiq_3f_srvs::Move >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::MoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotiq_3f_srvs::MoveResponse> should match
// service_traits::MD5Sum< ::robotiq_3f_srvs::Move >
template<>
struct MD5Sum< ::robotiq_3f_srvs::MoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotiq_3f_srvs::Move >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::MoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotiq_3f_srvs::MoveResponse> should match
// service_traits::DataType< ::robotiq_3f_srvs::Move >
template<>
struct DataType< ::robotiq_3f_srvs::MoveResponse>
{
  static const char* value()
  {
    return DataType< ::robotiq_3f_srvs::Move >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::MoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTIQ_3F_SRVS_MESSAGE_MOVE_H
