// Generated by gencpp from file robotiq_3f_srvs/SetMode.msg
// DO NOT EDIT!


#ifndef ROBOTIQ_3F_SRVS_MESSAGE_SETMODE_H
#define ROBOTIQ_3F_SRVS_MESSAGE_SETMODE_H

#include <ros/service_traits.h>


#include <robotiq_3f_srvs/SetModeRequest.h>
#include <robotiq_3f_srvs/SetModeResponse.h>


namespace robotiq_3f_srvs
{

struct SetMode
{

typedef SetModeRequest Request;
typedef SetModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMode
} // namespace robotiq_3f_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotiq_3f_srvs::SetMode > {
  static const char* value()
  {
    return "939409827c5731ec5346c99677bd2a1d";
  }

  static const char* value(const ::robotiq_3f_srvs::SetMode&) { return value(); }
};

template<>
struct DataType< ::robotiq_3f_srvs::SetMode > {
  static const char* value()
  {
    return "robotiq_3f_srvs/SetMode";
  }

  static const char* value(const ::robotiq_3f_srvs::SetMode&) { return value(); }
};


// service_traits::MD5Sum< ::robotiq_3f_srvs::SetModeRequest> should match
// service_traits::MD5Sum< ::robotiq_3f_srvs::SetMode >
template<>
struct MD5Sum< ::robotiq_3f_srvs::SetModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotiq_3f_srvs::SetMode >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::SetModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotiq_3f_srvs::SetModeRequest> should match
// service_traits::DataType< ::robotiq_3f_srvs::SetMode >
template<>
struct DataType< ::robotiq_3f_srvs::SetModeRequest>
{
  static const char* value()
  {
    return DataType< ::robotiq_3f_srvs::SetMode >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::SetModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotiq_3f_srvs::SetModeResponse> should match
// service_traits::MD5Sum< ::robotiq_3f_srvs::SetMode >
template<>
struct MD5Sum< ::robotiq_3f_srvs::SetModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotiq_3f_srvs::SetMode >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::SetModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotiq_3f_srvs::SetModeResponse> should match
// service_traits::DataType< ::robotiq_3f_srvs::SetMode >
template<>
struct DataType< ::robotiq_3f_srvs::SetModeResponse>
{
  static const char* value()
  {
    return DataType< ::robotiq_3f_srvs::SetMode >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::SetModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTIQ_3F_SRVS_MESSAGE_SETMODE_H
