// Generated by gencpp from file robotiq_3f_srvs/SetSpeed.msg
// DO NOT EDIT!


#ifndef ROBOTIQ_3F_SRVS_MESSAGE_SETSPEED_H
#define ROBOTIQ_3F_SRVS_MESSAGE_SETSPEED_H

#include <ros/service_traits.h>


#include <robotiq_3f_srvs/SetSpeedRequest.h>
#include <robotiq_3f_srvs/SetSpeedResponse.h>


namespace robotiq_3f_srvs
{

struct SetSpeed
{

typedef SetSpeedRequest Request;
typedef SetSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSpeed
} // namespace robotiq_3f_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotiq_3f_srvs::SetSpeed > {
  static const char* value()
  {
    return "0ac8fdc96972cecc8d4bedcd2935d6ea";
  }

  static const char* value(const ::robotiq_3f_srvs::SetSpeed&) { return value(); }
};

template<>
struct DataType< ::robotiq_3f_srvs::SetSpeed > {
  static const char* value()
  {
    return "robotiq_3f_srvs/SetSpeed";
  }

  static const char* value(const ::robotiq_3f_srvs::SetSpeed&) { return value(); }
};


// service_traits::MD5Sum< ::robotiq_3f_srvs::SetSpeedRequest> should match
// service_traits::MD5Sum< ::robotiq_3f_srvs::SetSpeed >
template<>
struct MD5Sum< ::robotiq_3f_srvs::SetSpeedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotiq_3f_srvs::SetSpeed >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::SetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotiq_3f_srvs::SetSpeedRequest> should match
// service_traits::DataType< ::robotiq_3f_srvs::SetSpeed >
template<>
struct DataType< ::robotiq_3f_srvs::SetSpeedRequest>
{
  static const char* value()
  {
    return DataType< ::robotiq_3f_srvs::SetSpeed >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::SetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotiq_3f_srvs::SetSpeedResponse> should match
// service_traits::MD5Sum< ::robotiq_3f_srvs::SetSpeed >
template<>
struct MD5Sum< ::robotiq_3f_srvs::SetSpeedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotiq_3f_srvs::SetSpeed >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::SetSpeedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotiq_3f_srvs::SetSpeedResponse> should match
// service_traits::DataType< ::robotiq_3f_srvs::SetSpeed >
template<>
struct DataType< ::robotiq_3f_srvs::SetSpeedResponse>
{
  static const char* value()
  {
    return DataType< ::robotiq_3f_srvs::SetSpeed >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::SetSpeedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTIQ_3F_SRVS_MESSAGE_SETSPEED_H
