// Generated by gencpp from file robotiq_3f_srvs/SetTorque.msg
// DO NOT EDIT!


#ifndef ROBOTIQ_3F_SRVS_MESSAGE_SETTORQUE_H
#define ROBOTIQ_3F_SRVS_MESSAGE_SETTORQUE_H

#include <ros/service_traits.h>


#include <robotiq_3f_srvs/SetTorqueRequest.h>
#include <robotiq_3f_srvs/SetTorqueResponse.h>


namespace robotiq_3f_srvs
{

struct SetTorque
{

typedef SetTorqueRequest Request;
typedef SetTorqueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTorque
} // namespace robotiq_3f_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotiq_3f_srvs::SetTorque > {
  static const char* value()
  {
    return "8194d85bcb7da4631dfd6a561184076a";
  }

  static const char* value(const ::robotiq_3f_srvs::SetTorque&) { return value(); }
};

template<>
struct DataType< ::robotiq_3f_srvs::SetTorque > {
  static const char* value()
  {
    return "robotiq_3f_srvs/SetTorque";
  }

  static const char* value(const ::robotiq_3f_srvs::SetTorque&) { return value(); }
};


// service_traits::MD5Sum< ::robotiq_3f_srvs::SetTorqueRequest> should match
// service_traits::MD5Sum< ::robotiq_3f_srvs::SetTorque >
template<>
struct MD5Sum< ::robotiq_3f_srvs::SetTorqueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotiq_3f_srvs::SetTorque >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::SetTorqueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotiq_3f_srvs::SetTorqueRequest> should match
// service_traits::DataType< ::robotiq_3f_srvs::SetTorque >
template<>
struct DataType< ::robotiq_3f_srvs::SetTorqueRequest>
{
  static const char* value()
  {
    return DataType< ::robotiq_3f_srvs::SetTorque >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::SetTorqueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotiq_3f_srvs::SetTorqueResponse> should match
// service_traits::MD5Sum< ::robotiq_3f_srvs::SetTorque >
template<>
struct MD5Sum< ::robotiq_3f_srvs::SetTorqueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotiq_3f_srvs::SetTorque >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::SetTorqueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotiq_3f_srvs::SetTorqueResponse> should match
// service_traits::DataType< ::robotiq_3f_srvs::SetTorque >
template<>
struct DataType< ::robotiq_3f_srvs::SetTorqueResponse>
{
  static const char* value()
  {
    return DataType< ::robotiq_3f_srvs::SetTorque >::value();
  }
  static const char* value(const ::robotiq_3f_srvs::SetTorqueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTIQ_3F_SRVS_MESSAGE_SETTORQUE_H
